source 'https://rubygems.org'

gem 'rake', '>=12.0.0'
gem 'rack', '>=2.0.3'
gem 'json', '>=2.1.0'
gem 'ansi', '>=1.5.0'
gem 'slim', '>=3.0.8'
gem 'nokogiri', '>=1.8.0'
gem 'builder', '>=3.2.0'

gem 'middleman', '>=4.2.1'
gem 'middleman-minify-html', '>=3.4.1'
gem 'middleman-syntax', '>=3.0.0'
gem 'middleman-robots', '>=1.3.2'
gem 'middleman-search_engine_sitemap'
gem 'middleman-sitemap-ping', '>=1.0.0'