source 'https://rubygems.org'

gem 'rake'
gem 'rack'
gem 'json'
gem 'ansi'
gem 'slim'
gem 'nokogiri'
gem 'builder'

gem 'middleman'
gem 'middleman-prismic'
gem 'middleman-minify-html'
gem 'middleman-syntax'
gem 'middleman-robots'
gem 'middleman-search_engine_sitemap'
gem 'middleman-sitemap-ping'