backend:
    name: github
    repo: wkwkrnht/middleman-by-wkwkrnht
    branch: master

media_folder: source/img/

collections:
- name: "blog" # Used in routes, e.g. /admin/collections/blog
  label: "Blog" # Used in the UI
  folder: "source/blog/articles" # The path to the folder where the documents are stored
  create: true
  slug: "{{slug}}.html" # Filename template i.e. title.html.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string", default: ""}
    - {label: "Publish Date", name: "date", widget: "datetime", default: ""}
    - {label: "Tags", name: "tags", widget: "string", default: "未分類", required: false}
    - {label: "Eyecatch", name: "eyecatch", widget: "image", default: "", required: false}
    - {label: "Author", name: "author", widget: "string", default: "wkwkrnht"}
    - {label: "Content", name: "body", widget: "markdown", default: ""}